### ISSUE TITLE
feedback on unemployment dashboard

### ISSUE THREAD

**Issue by trevorkwan** [UBC-MDS/DSCI532_Group112_Unemployment#39]
- a bit unclear on which countries the dashboard is representing

3 goals of the dashbaords:
- overall change in unemployment, which industry has grown/shrunk the most, is unemployment rate seasonal

purpose of the 3 graphs:
- 2nd graph: compare trends of industries
- 1st graph: compare between industries given a year range
- 3rd graph: compare trends of industries within a specific year by months

- title is more representative of 1st graph, comparing "across industries", 2nd and 3rd graph does more of comparing "across years" or "across months"

- given the option of both rate and count, the user may draw different conclusions depending if they look at rate or count. 

-subtitle specifies "rate" when both rate and count options are available

**Comment by marvinmin** [comment]
Thank you!
