### ISSUE TITLE
Peer Feedback (Derek & Andres)

### ISSUE THREAD

**Issue by dkruszew** [UBC-MDS/DSCI532_Group112_Unemployment#40]
Feedback:
- Interactive functionality is not helpful
- The slider bar in the Seasonal Unemployment Tab makes it seem like you are selecting a range instead of just one year to look at trends for.
- More space between Rate and Count Bubbles
- Idea: have an option to look at seasonal trends for all industries as one line.
- Idea: Have a dashed line for the total industry average that the individual industries can be compared to.
- Doesn't save filter criteria when switching between tabs

**Comment by lisebraaten** [comment]
Feedback on your dashboard:
- Fix Transportation & Utilities data so that the line shows up on the unemployment plots
- Remove 2010 from the seasonal unemployment plot since there is only data for first 2 months
- Zooming functionality in the plots is probably not necessary

Beautiful dashboard :)

**Comment by marvinmin** [comment]
Thank you for the feedbacks.
